name: enderchest
version: "${version}"
main: com.spectrasonic.enderchest.Main
api-version: "1.21"
authors: [Spectrasonic]
commands:
    enderchest:
        usage: /enderchest
        aliases:
            - ec
            - echest
        description: Open your EnderChest
        permission: enderchest.use
    enderbag:
        usage: /enderbag give <player>
        description: Gives you an EnderBag
        aliases:
            - ebag
        permission: enderbag.admin
permissions:
    enderbag.use:
        description: Allows players to open their EnderChest
        default: op
    enderbag.craft:
        description: Allows crafting of EnderBag
        default: true
    enderbag.admin:
        description: Allows admin commands
        default: op
